build: false
version: "{branch}-{build}"

environment:
  BOOST_INCLUDEDIR: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0
  PYTHON: C:\Python27

  matrix:
    - VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      BOOST_INCLUDEDIR: C:\Libraries\boost_1_59_0
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0

install:
  - call "%VS%" x86
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - pip install bfg9000
  - cinst ninja
  - git clone https://github.com/jimporter/mettle.git
  - cd mettle
  - copy ..\include\bencode.hpp include\bencode.hpp
  - 9k build --backend=ninja --prefix=C:\mettle
  - cd build
  - ninja install
  - cd ..\..
test_script:
  - set PATH=C:\mettle;%PATH%
  - set LIBRARY_PATH=C:\mettle
  - set CPPFLAGS=/WX /IC:\mettle
  - 9k build --backend=ninja
  - cd build
  - ninja test
